import type { Metadata } from "next";
import Link from "next/link";
import { AppHeader } from "../../components/app-header";
import { Arrow } from "../../components/brand";
import { RiverDivider } from "../../components/curves";
import { ProcessSteps } from "../../components/process-steps";
import { Footer, PageIntro } from "../../components/ui";

export const metadata: Metadata = { title: "How it works" };
export default function HowItWorksPage() {
  return <><AppHeader/><main id="main-content"><section className="section-shell how-it-works-hero"><PageIntro title="One observation. A shared next step."><p>You know your local stream. Together, we can build a clearer picture of what has changed.</p></PageIntro><div className="button-row"><Link className="button button-primary" href="/report/new">Report an observation <Arrow/></Link><Link className="button button-outline" href="/example">Explore an example</Link></div></section><section className="section-shell guide-steps" aria-label="The investigation process"><ProcessSteps/><p className="muted">You do not need a named river, a mapped stream, a meter, or an existing investigation to make a report.</p></section><section id="communities" className="role-section"><div className="section-shell"><h2>Different skills. A common purpose.</h2><div className="role-grid"><article><h3>Notice & contribute</h3><p>Describe what you observed, when, and where. A photo is welcome but optional. A coordinator reviews the report and connects it to a local investigation.</p></article><article><h3>Coordinate & collect</h3><p>Coordinators check what is known and organize feasible work. Qualified monitors collect traceable measurements with the right instruments and protocols.</p></article><article><h3>Review & revise</h3><p>Qualified reviewers evaluate evidence and assumptions. Decisions remain connected to their records, and can change when new evidence arrives.</p></article></div></div></section><section className="section-shell responsibility-section"><h2>Evidence first.<br/>Uncertainty visible.</h2><div><p>A photo can document a change. It cannot identify a pollutant or establish water safety. Conductivity alone does not identify a chemical or prove a source.</p><p>Source-area analysis needs a reviewed network, comparable measurements, and explicit uncertainty bounds. When those are missing, the investigation stays open and the next step is to build that foundation.</p><p>A reach that remains under consideration is not proven responsible. An excluded reach is incompatible under stated assumptions, not proven clean. New evidence can expand the area under consideration.</p><Link href="/example" className="text-link">See how an investigation changes <Arrow/></Link></div></section><section className="community-invitation"><RiverDivider/><div className="section-shell"><h2>Start with what you can safely observe.</h2><Link className="button button-outline" href="/report/new">Make a report <Arrow/></Link></div><p className="section-shell field-guidance">Stay on safe, permitted access routes. Do not enter the water or approach a suspected hazard to make a report. For an immediate threat, contact the appropriate local emergency service.</p></section></main><Footer/></>;
}
